In [1]:
import numpy as np

ARITHMETHIC OPEATIONS

In [5]:
arr = np.arange(1,11)
arr1 = np.arange(11,21)

In [6]:
arr+arr1

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [7]:
arr-arr1

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [8]:
arr*arr1

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [9]:
arr/arr1

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [10]:
arr//arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
arr**arr1

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       7766279631452241920])

In [12]:
arr%arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

BROADCASTING

In [13]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

MATRIX MANIPULATION

In [14]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [15]:
a1 * a2

array([[ 5, 12],
       [21, 32]])

In [16]:
a1 @ a2

array([[19, 22],
       [43, 50]])

In [17]:
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [18]:
a1.T

array([[1, 3],
       [2, 4]])

STACKING OF ARRAY

In [19]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [21]:
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [23]:
np.column_stack((a1,a2))

array([[1, 4],
       [2, 5],
       [3, 6]])

SPLITING

In [25]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.vsplit(arr,)