In [1]:
import numpy as np

In [2]:
#ID	 Age	Dept	Experience	Salary	Performance
data = np.array([
    [1001,24,3,2,4200,6],
    [1002,31,1,5,8000,8],
    [1003,45,2,20,15500,9],
    [1004,38,5,10,9500,7],
    [1005,29,3,7,7200,6],
    [1006,41,4,15,13400,8],
    [1007,22,1,1,3800,5],
    [1008,53,2,25,16000,10],
    [1009,36,5,12,9800,6],
    [1010,27,3,4,6200,7],
    [1011,50,4,28,17800,9],
    [1012,26,1,3,5900,6],
    [1013,48,2,22,16500,8],
    [1014,34,5,8,8300,5],
    [1015,43,4,19,14200,9],
    [1016,25,1,2,4600,6],
    [1017,39,3,9,8700,8],
    [1018,31,2,7,7200,7],
    [1019,58,5,30,19000,10],
    [1020,33,4,6,8000,5],
    [1021,40,2,18,14500,8],
    [1022,29,3,5,7100,6],
    [1023,54,1,25,16800,9],
    [1024,30,5,7,8600,8],
    [1025,46,4,21,15200,9],
    [1026,23,1,1,4000,5],
    [1027,37,3,10,9400,7],
    [1028,44,2,19,14000,8],
    [1029,28,5,4,6700,6],
    [1030,35,4,11,9900,7],
])
data

array([[ 1001,    24,     3,     2,  4200,     6],
       [ 1002,    31,     1,     5,  8000,     8],
       [ 1003,    45,     2,    20, 15500,     9],
       [ 1004,    38,     5,    10,  9500,     7],
       [ 1005,    29,     3,     7,  7200,     6],
       [ 1006,    41,     4,    15, 13400,     8],
       [ 1007,    22,     1,     1,  3800,     5],
       [ 1008,    53,     2,    25, 16000,    10],
       [ 1009,    36,     5,    12,  9800,     6],
       [ 1010,    27,     3,     4,  6200,     7],
       [ 1011,    50,     4,    28, 17800,     9],
       [ 1012,    26,     1,     3,  5900,     6],
       [ 1013,    48,     2,    22, 16500,     8],
       [ 1014,    34,     5,     8,  8300,     5],
       [ 1015,    43,     4,    19, 14200,     9],
       [ 1016,    25,     1,     2,  4600,     6],
       [ 1017,    39,     3,     9,  8700,     8],
       [ 1018,    31,     2,     7,  7200,     7],
       [ 1019,    58,     5,    30, 19000,    10],
       [ 1020,    33,     4,   

In [3]:
#What is the shape, size, and dtype of data
data.shape

(30, 6)

In [4]:
#Print the first 5 rows and last 5 rows of the array.
print(data[0:5,:])
print(data[-5:,:])

[[ 1001    24     3     2  4200     6]
 [ 1002    31     1     5  8000     8]
 [ 1003    45     2    20 15500     9]
 [ 1004    38     5    10  9500     7]
 [ 1005    29     3     7  7200     6]]
[[ 1026    23     1     1  4000     5]
 [ 1027    37     3    10  9400     7]
 [ 1028    44     2    19 14000     8]
 [ 1029    28     5     4  6700     6]
 [ 1030    35     4    11  9900     7]]


In [5]:
#Extract the Age column only.
data[:,1]

array([24, 31, 45, 38, 29, 41, 22, 53, 36, 27, 50, 26, 48, 34, 43, 25, 39,
       31, 58, 33, 40, 29, 54, 30, 46, 23, 37, 44, 28, 35])

In [6]:
#Extract the Salary column for the first 10 employees.
data[:10,4]

array([ 4200,  8000, 15500,  9500,  7200, 13400,  3800, 16000,  9800,
        6200])

In [7]:
#How many unique department codes exist?
np.unique(data[:,2])

array([1, 2, 3, 4, 5])

In [8]:
#Select all employees from Department 3.
data[data[:,2] == 3]

array([[1001,   24,    3,    2, 4200,    6],
       [1005,   29,    3,    7, 7200,    6],
       [1010,   27,    3,    4, 6200,    7],
       [1017,   39,    3,    9, 8700,    8],
       [1022,   29,    3,    5, 7100,    6],
       [1027,   37,    3,   10, 9400,    7]])

In [9]:
#Get all employees older than 50 years.
data[data[:,1]>50]

array([[ 1008,    53,     2,    25, 16000,    10],
       [ 1019,    58,     5,    30, 19000,    10],
       [ 1023,    54,     1,    25, 16800,     9]])

In [10]:
#Select rows for employees with Performance > 8 and Salary > 15000.
data[(data[:,5]>8) & (data[:,4]>15000)]

array([[ 1003,    45,     2,    20, 15500,     9],
       [ 1008,    53,     2,    25, 16000,    10],
       [ 1011,    50,     4,    28, 17800,     9],
       [ 1019,    58,     5,    30, 19000,    10],
       [ 1023,    54,     1,    25, 16800,     9],
       [ 1025,    46,     4,    21, 15200,     9]])

In [11]:
#Retrieve IDs of employees with less than 5 years of experience.
data[:,0][data[:,3]<5]

array([1001, 1007, 1010, 1012, 1016, 1026, 1029])

In [12]:
#Get all employees from Department 2, columns only for Age, Salary, and Performance.
data[:,[1,4,5]][data[:,2] == 2]

array([[   45, 15500,     9],
       [   53, 16000,    10],
       [   48, 16500,     8],
       [   31,  7200,     7],
       [   40, 14500,     8],
       [   44, 14000,     8]])

In [13]:
#How many employees earn more than $10,000?
len(data[data[:,4]>10000])

11

In [14]:
#Find average salary of employees under 30.
np.mean(data[:,4][data[:,1]<30])

np.float64(5522.222222222223)

In [15]:
#Count how many employees have Experience ≥ 10 years and Performance ≥ 7.
len(data[(data[:,3] >= 10 ) & (data[:,-1] >= 7)])

14

In [16]:
#Replace all salaries below 4000 with 4000 (minimum wage policy).
data[:,4][data[:,-2] < 4000] = 4000
data

array([[ 1001,    24,     3,     2,  4200,     6],
       [ 1002,    31,     1,     5,  8000,     8],
       [ 1003,    45,     2,    20, 15500,     9],
       [ 1004,    38,     5,    10,  9500,     7],
       [ 1005,    29,     3,     7,  7200,     6],
       [ 1006,    41,     4,    15, 13400,     8],
       [ 1007,    22,     1,     1,  4000,     5],
       [ 1008,    53,     2,    25, 16000,    10],
       [ 1009,    36,     5,    12,  9800,     6],
       [ 1010,    27,     3,     4,  6200,     7],
       [ 1011,    50,     4,    28, 17800,     9],
       [ 1012,    26,     1,     3,  5900,     6],
       [ 1013,    48,     2,    22, 16500,     8],
       [ 1014,    34,     5,     8,  8300,     5],
       [ 1015,    43,     4,    19, 14200,     9],
       [ 1016,    25,     1,     2,  4600,     6],
       [ 1017,    39,     3,     9,  8700,     8],
       [ 1018,    31,     2,     7,  7200,     7],
       [ 1019,    58,     5,    30, 19000,    10],
       [ 1020,    33,     4,   

In [17]:
#Find all employees who have Age < 25 and Experience > 5.
data[(data[:,1]<25) & (data[:,3]>5)]

array([], shape=(0, 6), dtype=int64)

In [18]:
#Compute mean, median, min, max of salaries.
print(np.mean(data[:,4]))
print(np.median(data[:,4]))
print(np.max(data[:,4]))
print(np.min(data[:,4]))

10340.0
9050.0
19000
4000


In [19]:
#Find mean performance score per department.
for i in np.unique(data[:,2]):
    val = np.mean(data[:,5][data[:,2] == i ])
    print(f"{i} ---- {val}")

1 ---- 6.5
2 ---- 8.333333333333334
3 ---- 6.666666666666667
4 ---- 7.833333333333333
5 ---- 7.0


In [20]:
#Find highest-paid employee ID and their salary.
data[:,0][data[:,4] == np.max(data[:,4])]

array([1019])

In [21]:
#Get standard deviation of years of experience.
np.std(data[:,3])

np.float64(8.562450324267905)

In [22]:
#Find the average salary per department using NumPy grouping logic.
for i in np.unique(data[:,2]):
    print(f"{i} ---- {np.mean(data[:,4][data[:,2] == i ])}")

1 ---- 7216.666666666667
2 ---- 13950.0
3 ---- 7133.333333333333
4 ---- 13083.333333333334
5 ---- 10316.666666666666


In [23]:
#Sort the entire dataset by Salary (ascending).
data[np.argsort(data[:,4])]

array([[ 1007,    22,     1,     1,  4000,     5],
       [ 1026,    23,     1,     1,  4000,     5],
       [ 1001,    24,     3,     2,  4200,     6],
       [ 1016,    25,     1,     2,  4600,     6],
       [ 1012,    26,     1,     3,  5900,     6],
       [ 1010,    27,     3,     4,  6200,     7],
       [ 1029,    28,     5,     4,  6700,     6],
       [ 1022,    29,     3,     5,  7100,     6],
       [ 1018,    31,     2,     7,  7200,     7],
       [ 1005,    29,     3,     7,  7200,     6],
       [ 1002,    31,     1,     5,  8000,     8],
       [ 1020,    33,     4,     6,  8000,     5],
       [ 1014,    34,     5,     8,  8300,     5],
       [ 1024,    30,     5,     7,  8600,     8],
       [ 1017,    39,     3,     9,  8700,     8],
       [ 1027,    37,     3,    10,  9400,     7],
       [ 1004,    38,     5,    10,  9500,     7],
       [ 1009,    36,     5,    12,  9800,     6],
       [ 1030,    35,     4,    11,  9900,     7],
       [ 1006,    41,     4,   

In [26]:
#Get the top 10 highest salaries and corresponding IDs.
data[np.argsort(data[:,4])[::-1]][:10,[0,4]]

array([[ 1019, 19000],
       [ 1011, 17800],
       [ 1023, 16800],
       [ 1013, 16500],
       [ 1008, 16000],
       [ 1003, 15500],
       [ 1025, 15200],
       [ 1021, 14500],
       [ 1015, 14200],
       [ 1028, 14000]])

In [29]:
#Find the index (row) of the employee with maximum performance score.
np.argmax(data[:,5])

np.int64(7)

In [38]:
#Sort employees by Department, then by Performance (descending).
data[np.lexsort((-data[:,5],data[:,2]))]

array([[ 1023,    54,     1,    25, 16800,     9],
       [ 1002,    31,     1,     5,  8000,     8],
       [ 1012,    26,     1,     3,  5900,     6],
       [ 1016,    25,     1,     2,  4600,     6],
       [ 1007,    22,     1,     1,  4000,     5],
       [ 1026,    23,     1,     1,  4000,     5],
       [ 1008,    53,     2,    25, 16000,    10],
       [ 1003,    45,     2,    20, 15500,     9],
       [ 1013,    48,     2,    22, 16500,     8],
       [ 1021,    40,     2,    18, 14500,     8],
       [ 1028,    44,     2,    19, 14000,     8],
       [ 1018,    31,     2,     7,  7200,     7],
       [ 1017,    39,     3,     9,  8700,     8],
       [ 1010,    27,     3,     4,  6200,     7],
       [ 1027,    37,     3,    10,  9400,     7],
       [ 1001,    24,     3,     2,  4200,     6],
       [ 1005,    29,     3,     7,  7200,     6],
       [ 1022,    29,     3,     5,  7100,     6],
       [ 1011,    50,     4,    28, 17800,     9],
       [ 1015,    43,     4,   

In [48]:
#Increase salaries of employees in Department 1 by 10%.
data[:,4][data[:,2] == 1] *= .10

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'