In [1]:
import numpy as np

Basic array creation

In [7]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [9]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

Random generation functions 

In [19]:
np.random.rand(10)

array([0.28923075, 0.78830374, 0.10408773, 0.62763413, 0.89695859,
       0.15897312, 0.77457358, 0.0210564 , 0.66831646, 0.68896848])

In [20]:
np.random.randn(10)

array([ 0.43548144,  0.70123498,  1.33842873, -0.30633873, -0.58173442,
       -0.35402742,  0.5086054 ,  0.71710964,  0.73943486,  0.20169637])

In [63]:
np.random.randint(5)

1

In [69]:
np.random.randint(1,11,10)

array([10,  8,  2,  9,  6,  9,  6,  6,  1,  1], dtype=int32)

attributes

In [72]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr.shape

(3, 3)

In [74]:
arr.size

9

In [75]:
arr.dtype

dtype('int64')

Array Methods

In [76]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr.min()

np.int64(1)

In [78]:
arr.max()

np.int64(9)

In [79]:
arr.sum()

np.int64(45)

In [81]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [83]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [84]:
arr.mean()

np.float64(5.0)

In [85]:
arr.argmax()

np.int64(8)

In [86]:
arr.argmin()

np.int64(0)

In [87]:
arr.std()

np.float64(2.581988897471611)

Reshape abd resizing

In [92]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [94]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])