In [1]:
import numpy as np

INDEXING AND SLICING VECTORS

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[0]

np.int64(11)

In [4]:
arr[::]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[0:5:1]

array([11, 12, 13, 14, 15])

INDEXING AND SLICING OF MATRIX

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[0]

array([1, 2, 3, 4, 5])

In [9]:
arr[0,0]

np.int64(1)

In [10]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [11]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [12]:
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

BOOLEAN INDEXING


In [ ]:
arr = np.arange()